export function createDefaultTextLayer(text = "NEW TEXT", y = 0.5) {
  return {
    id: `layer-${Math.random().toString(36).slice(2, 9)}`,
    type: "text",
    text,
    x: 0.5,
    y,
    maxWidth: 0.82,
    fontFamily: "Impact",
    fontSize: 56,
    fontWeight: 700,
    letterSpacing: 0,
    lineHeight: 1.05,
    color: "#ffffff",
    strokeColor: "#000000",
    strokeWidth: 6,
    shadowColor: "rgba(0,0,0,0.45)",
    shadowBlur: 0,
    shadowOffsetX: 0,
    shadowOffsetY: 0,
    align: "center",
    autoSize: true,
    backgroundColor: "rgba(0,0,0,0)",
    backgroundPadding: 0,
    backgroundRadius: 0,
    rotation: 0,
    scale: 1,
    opacity: 1,
    lock: false,
    hidden: false,
  };
}

export function createStickerLayer(emoji = "🔥") {
  return {
    id: `layer-${Math.random().toString(36).slice(2, 9)}`,
    type: "sticker",
    text: emoji,
    x: 0.7,
    y: 0.32,
    maxWidth: 0.4,
    fontFamily: '"Apple Color Emoji", "Segoe UI Emoji", sans-serif',
    fontSize: 72,
    fontWeight: 400,
    letterSpacing: 0,
    lineHeight: 1,
    color: "#ffffff",
    strokeColor: "#000000",
    strokeWidth: 0,
    shadowColor: "rgba(0,0,0,0.18)",
    shadowBlur: 8,
    shadowOffsetX: 0,
    shadowOffsetY: 6,
    align: "center",
    autoSize: false,
    backgroundColor: "rgba(0,0,0,0)",
    backgroundPadding: 0,
    backgroundRadius: 0,
    rotation: 0,
    scale: 1,
    opacity: 1,
    lock: false,
    hidden: false,
  };
}

export function createImageLayer(src, fileName = "") {
  return {
    id: `layer-${Math.random().toString(36).slice(2, 9)}`,
    type: "image",
    imageSrc: src,
    fileName,
    x: 0.5,
    y: 0.5,
    scale: 1,
    rotation: 0,
    opacity: 1,
    baseWidth: 0.28,
    shadowColor: "rgba(0,0,0,0.18)",
    shadowBlur: 8,
    shadowOffsetX: 0,
    shadowOffsetY: 4,
    lock: false,
    hidden: false,
  };
}
